[boot]
systemd = true          # [S-005]
protectBinfmt = true    # [S-004]

[automount]
enabled = false         # [S-003]
mountFsTab = true       # [S-019]
root = /mnt/
uid = 1000
gid = 1000

[network]
hostname = __DistroName__
generateHosts = true
generateResolvConf = true

[interop]
enabled = false             # [S-001]
appendWindowsPath = false   # [S-002]

[user]
default = __Username__  # [S-006]

[gpu]
enabled = __GpuEnabled__   # [S-014]

[time]
useWindowsTimezone = true
