[boot]
systemd = true
protectBinfmt = true

[automount]
enabled = false
mountFsTab = true
root = /mnt/
uid = 1000
gid = 1000

[network]
hostname = __DistroName__
generateHosts = true
generateResolvConf = true

[interop]
enabled = false
appendWindowsPath = false

[user]
default = __Username__

[gpu]
enabled = true

[time]
useWindowsTimezone = true
